# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell@0.7.0" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "b94a65c71bb8ec683edc3bc791492eb819798a08a295f0e64e93b05aa7dd7eb7"
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "4bb8c69417f3c7c5156f9fd76f0dedf0e078ed245d02802110330cb100dc3884"
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f49d3f4999e5125341c893bb84f30522cc207a5bed3ed3d9ab6d25742e01e65"
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "4368db13a0a876cb7b28c08d9b96eb44b05d82947a118e05eb495c5b828dbdaf"
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
  end

  name "devcell@0.7.0"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell-dev",
    ]

  binary "cell"

  # No zap stanza required

end
