# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "3b87f8c589dca924d29ec4509e9baa2da3e8b68cbf698e283e0db72474671ad3"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5cac7728eb16c453ec16e54e536ec9d07b9506d5125f60a08b008028e2b37952"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d973ee09e12de05c3476ac6beaadc2333bdf4adb1ed85820cbe11622940c58f"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "8ace00ecb8e4d33edf03ef7e37a1f9a133fb8864788516658137fe56468fc6c2"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
  end

  name "devcell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/devcell-sh/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required

end
