# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "0098d637604f884bb91bfd9d19637c7416f8d75c686b8be39e17e78edc43fda7"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "21deb523cd44ee82525f9b1e3735cab6770b694c5d304bcf871bb2505b5de16d"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ecea64648166eefaf2080a597d7986b5c3b2eb6af879e4c1ed11befe60fc261b"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "aeb072e4e20bed10c47d49a784c234040e6f420ab3309b9cc9314aabc15c4d87"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
  end

  name "devcell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/devcell-sh/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required

end
