# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev" do
  version "0.0.0"

  on_macos do
    on_arm do
      sha256 "7c108b3e29991cad7f2f38eb1301e2d1ac32d6ab2f879b80a06633094833b4ad"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "d287d34e9cbf3c81936cd9eb90d1ac302c7a86b15542fdf292857c8ff6a5877f"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ac4625c73ef02d80a22ca590e7fa444d61703f3a6e05a98a6b28e606c5092cf"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "643a2565ddd09e22cf0c2d86b52e3e24f3fb863a6eebc96c71c34b48e0322049"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
  end

  name "devcell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/devcell-sh/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required
end
