# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_arm do
      sha256 "db2f3de28fd07fcbb3b7f114aba0ceef8dae2993076b767c80bbca93d2ddba62"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "5095968846431b8d98cfec2e8f8038a3cccf621360de0939d4e77fa9f83cfd47"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fde15c41656978c231529f7cda402bf8d7e1cbe4dccd47f37c5986aa88b9e69a"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "448963860c9dd7db5bd482c071657ebcda18df318c02b076c6b27fcc7d97c0fa"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
  end

  name "devcell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/devcell-sh/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required
end
