# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "abfea193d719929085478b570dccd88d766dc41f6666cf9becc734936a6aba1f"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "2a3701bdac764af5983c18d4e5cb276941ee518fc0462542b16156db73aad40c"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "834b7f4b6838885b292935a8beaf2ea0af743798ac60675c9c083c0468e53c1c"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "37366c734d61c78a3343c811265643a203acd9f4f8bf4ea8039972f2d1b88026"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
  end

  name "devcell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/devcell-sh/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required

end
