# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev" do
  version "0.0.0"

  on_macos do
    on_arm do
      sha256 "a9579d7d85365310abecd382a9be96f211c821e3332b5cd2c86c45f187449bee"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "87a32e3391c2e322cbea1d16a7efb0b50ccbbd1ad6fdbbbc375d848a9078d699"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "358b79fc309b7385639381e5130cd8b163e2a29de25e2ba1e3627231f52b3008"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "2210ef85ec009a2de0a5b8b3ebb7007e3dc9794e65f233786984bcffcd2c47ae"
      url "https://github.com/devcell-sh/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
    end
  end

  name "devcell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/devcell-sh/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required
end
